logRequests: false

database:
  driverClass: 
  url: 
  user: 
  password: 
  validationQuery: /* Health Check */ SELECT 1 FROM DUAL
  properties:
    hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate.connection.charSet: UTF-8

logging:
  level: INFO
  loggers:
    org.hibernate.SQL: DEBUG
    org.glassfish.jersey.filter.LoggingFilter: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
  appenders:
    - type: console
